insert into T_BUSLINIE(BUSNR) VALUES (2004);
insert into T_BUSLINIE(BUSNR) VALUES (2006);
insert into T_BUSLINIE(BUSNR) VALUES (2010);
insert into T_BUSLINIE(BUSNR) VALUES (2012);

insert into T_HALTESTELLE(BEZEICHNUNG) VALUES ('Schule');
insert into T_HALTESTELLE(BEZEICHNUNG) VALUES ('Bahnhof');
insert into T_HALTESTELLE(BEZEICHNUNG) VALUES ('Tierarzt');
